/**
 * This file is autogenerated.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericModulesDeclaration } from "~~/utils/scaffold-move/module";

const externalModules = {} as const;

export default externalModules satisfies GenericModulesDeclaration;
